export { default as user } from './UserRoutes'
export { default as auth } from './AuthRoutes'
export { default as changePassword } from './ChangePasswordRoutes'
export { default as post } from './PostRoutes'
export { default as scales } from './ScalesRoutes'
export { default as songs } from './SoungRotes'
export { default as messages } from './MessageRoutes'
